In [4]:
# classification = keras.utils.to_categorical
import pandas as pd 
from sklearn.ensemble import RandomForestClassifier
import matplotlib.pyplot as plt 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler as mini
from keras.utils import to_categorical
import os
os.environ['KERAS_BACKEND' ] = 'tensorflow'
os.environ['MKL_THREADING_LAYER'] = 'GNU'
import keras as ks
from keras.models import Sequential
from keras.layers import Dense
from keras.callbacks import TensorBoard
import keras
import pandas as pd
import numpy as np
from keras import optimizers
from keras.utils import to_categorical
from keras.models import Model
from keras.layers import Input, Dense
from keras.layers.normalization import BatchNormalization
from keras.layers.core import Dropout, Activation
from sklearn.preprocessing import MinMaxScaler
import time 




# Set seed for reproducibility
NAME = "MLP_Single_merge_Overfitting_practice"
np.random.seed(0)
print("Loading data...")
# Load the data from the CSV files
NAME = 'MLP_CLASS'
data = pd.read_csv('../stocks_data//BTC-USD.csv')
df0,df1 = data.shape[0], data.shape[1] 
print('Bitcoin Data Has {} Transactions with {} features'.format(df0,df1))
data= data.drop(['Date'], axis =1)
data = data.drop('Adj Close',axis=1)

X= data.drop(['High'],axis=1)
# mini= mini(feature_range=(-1,1)) 
# X = mini.fit_transform(X)

y= data['High'] 
y = to_categorical(y)
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=.67) 
# prediction_data = pd.read_csv('test.csv', header=0)
# print('original prediction data shape: {},\t{} \n\n \t:'.format(prediction_data.shape[0],prediction_data.shape[1]))

# complete_training_data = pd.concat([training_data, prediction_data])
# pd.DataFrame(complete_training_data)

# # Transform the loaded CSV data into numpy arrays

# x_prediction = prediction_data
# x_prediction = mini.fit_transform(x_prediction)

batch_size = 710

dropout = 0.2

visible = Input(shape=(4,))
hidden1 = Dense(5, activation='sigmoid')(visible)
hidden1 = Dense(5, activation='sigmoid')(hidden1)
hidden1 = Dense(5, activation='sigmoid')(hidden1)
hidden1 = Dense(5, activation='sigmoid')(hidden1)
hidden1 = Dense(5, activation='sigmoid')(hidden1)
hidden1 = Dense(5, activation='sigmoid')(hidden1)
hidden2 = Dense(5, activation='sigmoid')(hidden1)
hidden2 = Dense(5, activation='sigmoid')(hidden2)
hidden2 = Dense(5, activation='sigmoid')(hidden2)
hidden2 = Dense(5, activation='sigmoid')(hidden2)
hidden2 = Dense(5, activation='sigmoid')(hidden2)
hidden2 = Dense(5, activation='sigmoid')(hidden2)
hidden2 = Dense(5, activation='sigmoid')(hidden2)
hidden3 = Dense(5, activation='sigmoid')(hidden2)
hidden3 = Dense(5, activation='sigmoid')(hidden3)
hidden3 = Dense(5, activation='sigmoid')(hidden3)
hidden3 = Dense(5, activation='sigmoid')(hidden3)
merge = keras.layers.concatenate([hidden1,hidden2,hidden3], axis=1)
hidden4 = Dense(5,activation='sigmoid')(merge)
output = Dense(19871, activation='sigmoid')(hidden4)
model = Model(inputs=visible, outputs=output)
model.compile(loss='binary_crossentropy',optimizer='rmsprop')
model.summary()
tensorboard = TensorBoard(log_dir="logs/{}".format(NAME))
model.fit(X_train,y_train,batch_size=batch_size,epochs=10,validation_split=0.33,callbacks=[tensorboard])


y_prediction = model.predict(X_test)
evaluate = model.evaluate(X_test,y_prediction)

probabilities = y_prediction[:, 1]
print("- probabilities:", probabilities[1:6])

# We can see the probability does seem to be good at predicting the
# true target correctly.
# print("- target:", prediction_data['target_bernie'][1:6])
# print("- rounded probability:", [np.round(p) for p in probabilities][1:6])

# # But overall the accuracy is very low.
# correct = [
# np.round(x) == y
# for (x, y) in zip(probabilities, prediction_data['target_bernie'])
# ]
# print("- accuracy: ", sum(correct) / float(prediction_data.shape[0]))

# tournament_corr = np.corrcoef(prediction_data['target_bernie'],
#   prediction_data['target_elizabeth'])
# print("- bernie vs elizabeth corr:", tournament_corr)
# # You can see that target_elizabeth is accurate using the bernie model as well.
# correct = [
# np.round(x) == y
# for (x, y) in zip(probabilities, prediction_data['target_elizabeth'])
# ]
# print("- elizabeth using bernie:",
#   sum(correct) / float(prediction_data.shape[0]))

# Numerai measures models on logloss instead of accuracy. The lower the logloss the better.
# Numerai only pays models with logloss < 0.693 on the live portion of the tournament data.)

print("- validation logloss:",
model.evaluate(X_test,y_prediction))

results = y_prediction[:, 1]
results_df = pd.DataFrame(data={'target':results})

# joined = pd.DataFrame(ids).join(results_df)
pd.DataFrame(results_df[:5])


print("Writing predictions to predictions.csv")
path = 'predictions_{:}_{}_1'.format(time.strftime("%Y-%m-%d_%Hh%Mm%Ss", time.gmtime()),NAME) + '.csv'
print()
print("Writing predictions to " + path.strip())
results_df.to_csv(path,float_format='%.15f', index=False)
# bata = pd.read_csv('../stocks_data/BTC-USD.csv')
# date = bata['Date']
# data = [go.Scatter(x=date, y=y)]
# print(bata[3274:3275])
# py.iplot(data, filename = 'time-series-simple')



Loading data...
Bitcoin Data Has 3275 Transactions with 7 features
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_2 (InputLayer)            (None, 4)            0                                            
__________________________________________________________________________________________________
dense_20 (Dense)                (None, 5)            25          input_2[0][0]                    
__________________________________________________________________________________________________
dense_21 (Dense)                (None, 5)            30          dense_20[0][0]                   
__________________________________________________________________________________________________
dense_22 (Dense)                (None, 5)            30          dense_21[0][0]                   
__________________________________________

In [8]:
import plotly.plotly as py
import plotly.graph_objs as go
import plotly
from datetime import datetime
plotly.tools.set_credentials_file(username='Gamma-AI1011', api_key='KoXH9I7ffpwUueVaa7TT')

In [9]:
# print('ACTUAL STOCK DATA')
# bata = pd.read_csv('../stocks_data/BTC-USD.csv')
# date = bata['Date']
# data = [go.Scatter(x=date, y=y)]
# print(bata[3274:3275])
# py.iplot(data, filename = 'time-series-simple')

In [12]:
print(X.shape)
future_x = X 
X = X[3270:3275] 
# future_x = X[-1]
# x = X[:-1]
bata = pd.read_csv('../stocks_data/BTC-USD.csv')
date = bata['Date']
date = date[3274:3275] 

(5, 4)


In [11]:
open = bata['Open']  
high= model.predict(future_x) 
low = bata['Low'] 
close = bata['Close']
trace = go.Candlestick(x=X_test,
                open=open,
                high=high,
                low=low, 
                close=close) 

layout = go.Layout(
    xaxis = dict(
        rangeslider = dict(
            visible = False
        )
    )
)
data = [trace]
print('PREDICTED HIGH') 
print(high)
fig = go.Figure(data=data,layout=layout)
py.iplot(fig, filename='simple_candlestick_without_range_slider')


PREDICTED HIGH
[[0.46385664 0.459377   0.47112462 ... 0.47242975 0.46594936 0.4644952 ]
 [0.4638567  0.45937717 0.47112474 ... 0.47242987 0.46594954 0.46449527]
 [0.4638567  0.45937732 0.47112483 ... 0.47242993 0.46594974 0.46449536]
 ...
 [0.4638567  0.45937732 0.47112483 ... 0.47242993 0.46594974 0.46449536]
 [0.4638567  0.45937732 0.47112483 ... 0.47242993 0.46594974 0.46449536]
 [0.4638567  0.45937732 0.47112483 ... 0.47242993 0.46594974 0.46449536]]


KeyboardInterrupt: 

In [1]:
import os
os.environ['KERAS_BACKEND' ] = 'tensorflow'
os.environ['MKL_THREADING_LAYER'] = 'GNU'
import keras as ks
from keras.models import Sequential
from keras.layers import Dense
from keras.callbacks import TensorBoard
import keras
import pandas as pd
import numpy as np
from keras import optimizers
from keras.utils import to_categorical
from keras.models import Model
from keras.layers import Input, Dense
from keras.layers.normalization import BatchNormalization
from keras.layers.core import Dropout, Activation
from sklearn.preprocessing import MinMaxScaler
import time 


def main():

    # Set seed for reproducibility
    NAME = "MLP"
    np.random.seed(0)



    print("Loading data...")

    # Load the data from the CSV files

    training_data = pd.read_csv('numerai_training_data.csv', header=0)
    print('original train data shape: {},\t{} \n\n \t:'.format(training_data.shape[0],training_data.shape[1]))

    prediction_data = pd.read_csv('numerai_tournament_data.csv', header=0)
    print('original prediction data shape: {},\t{} \n\n \t:'.format(prediction_data.shape[0],prediction_data.shape[1]))
    
    complete_training_data = pd.concat([training_data, prediction_data])
    print('total training / valdation shape {}'.format(complete_training_data))
    
    



    # Transform the loaded CSV data into numpy arrays

    features = [f for f in list(training_data) if "feature" in f]
    print(features)

    X = training_data[features]
    mini= MinMaxScaler(feature_range=(0,1)) 
    X = mini.fit_transform(X)
#     X = X.values
    Y = training_data["target"]
    Y= keras.utils.to_categorical(Y,2) 

    x_prediction = prediction_data[features]
    x_prediction = mini.fit_transform(x_prediction)

    ids = prediction_data["id"]

#     X = X.values

#     Y = to_categorical(Y, num_classes=2)

    

    batch_size = 710

    dropout = 0.2

    

    m_in = Input(shape=(50,))

    m1 = Dense(50,)(m_in)
    m1 = Activation('relu')(m1)
    m1 = BatchNormalization(momentum=.99999,axis=-1)(m1)

    m2 = Dense(100)(m1)
    m2 = Activation('relu')(m2)
    m2 = BatchNormalization(momentum=.999,axis=-1)(m2)
    
    m3 = Dense(25)(m2)
    m3 = Activation('relu')(m3)
    
    m3 = Dense(25)(m3)
    m3 = Dropout(dropout)(m3) 
    m3 = Activation('relu')(m3)
    
    m3 = Dense(25)(m3)
    m3 = Activation('relu')(m3)
    m3 = BatchNormalization(momentum=.99,axis=-1)(m3)
    
    m3 = Dense(100)(m3)
    m3 = Activation('relu')(m3)
    
    m3 = Dense(25)(m3)
    m3 = Activation('relu')(m3) 
    
    m4 = Dense(25)(m3)
    m4 = Activation('relu')(m4) 
    m4 = Dropout(dropout)(m4) 
    m4 = BatchNormalization(momentum=.9,axis=-1)(m4)

    
    
    m5 = Dense(2)(m4)
    m_out = Activation('sigmoid')(m5)

    model = Model(inputs=m_in, outputs=m_out)



    model.compile(loss='binary_crossentropy',optimizer='rmsprop')
    tensorboard = TensorBoard(log_dir="logs/{}".format(NAME))
    model.fit(X,Y,batch_size=batch_size,epochs=10,validation_split=0.33,callbacks=[tensorboard])
    
    

    

    y_prediction = model.predict(x_prediction)
    evaluate = model.evaluate(x_prediction,y_prediction)
    
    probabilities = y_prediction[:, 1]
    print("- probabilities:", probabilities[1:6])

    # We can see the probability does seem to be good at predicting the
    # true target correctly.
    print("- target:", prediction_data['target'][1:6])
    print("- rounded probability:", [np.round(p) for p in probabilities][1:6])

    # But overall the accuracy is very low.
    correct = [
        np.round(x) == y
        for (x, y) in zip(probabilities, prediction_data['target'])
    ]
    print("- accuracy: ", sum(correct) / float(prediction_data.shape[0]))

    # The targets for each of the tournaments are very correlated.
    tournament_corr = np.corrcoef(prediction_data['target'],
                                  prediction_data['target_elizabeth'])
    print("- bernie vs elizabeth corr:", tournament_corr)
    # You can see that target_elizabeth is accurate using the bernie model as well.
    correct = [
        np.round(x) == y
        for (x, y) in zip(probabilities, prediction_data['target_elizabeth'])
    ]
    print("- elizabeth using bernie:",
          sum(correct) / float(prediction_data.shape[0]))

    # Numerai measures models on logloss instead of accuracy. The lower the logloss the better.
    # Numerai only pays models with logloss < 0.693 on the live portion of the tournament data.)

    print("- validation logloss:",
          model.evaluate(x_prediction,y_prediction))

    results = y_prediction[:, 1]

    # -----

    

    results_df = pd.DataFrame(data={'probability_bernie':results})

    joined = pd.DataFrame(ids).join(results_df)
    pd.DataFrame(joined[:5])


    print("Writing predictions to predictions.csv")

    # Save the predictions out to a CSV file
    path = 'predictions_{:}'.format(time.strftime("%Y-%m-%d_%Hh%Mm%Ss", time.gmtime())) + '.csv'
    print()
    print("Writing predictions to " + path.strip())
    # # Save the predictions out to a CSV file
    joined.to_csv(path,float_format='%.15f', index=False)


    # Now you can upload these predictions on numer.ai





if __name__ == '__main__':

    main()

Using TensorFlow backend.


Loading data...
original train data shape: 502732,	60 

 	:
original prediction data shape: 333917,	60 

 	:
total training / valdation shape                       id   era data_type  feature1  feature2  feature3  \
0       n0003126ff2349f6  era1     train   0.54836   0.31077   0.37524   
1       n003d773d29b57ec  era1     train   0.34712   0.40275   0.42747   
2       n0074df2dc6810b6  era1     train   0.50871   0.48639   0.47544   
3       n0090630f530903e  era1     train   0.61363   0.40268   0.53779   
4       n00af19089546fe9  era1     train   0.30704   0.47273   0.54495   
5       n011d2da12b1e735  era1     train   0.52336   0.59136   0.60506   
6       n014149cadeee55d  era1     train   0.30875   0.62510   0.35229   
7       n0148a4dcf539aba  era1     train   0.40632   0.30590   0.43227   
8       n015855690d31908  era1     train   0.48193   0.27060   0.50228   
9       n0169447f4d6a10e  era1     train   0.51191   0.53663   0.42109   
10      n01703ba4eff8fe7  era1     train   0

Train on 336830 samples, validate on 165902 samples
Epoch 1/10
336830/336830 [==============================] - 7s 21us/step - loss: 0.7100 - val_loss: 0.6933
Epoch 2/10
336830/336830 [==============================] - 7s 20us/step - loss: 0.6951 - val_loss: 0.6930
Epoch 3/10
336830/336830 [==============================] - 6s 19us/step - loss: 0.6928 - val_loss: 0.6937
Epoch 4/10
336830/336830 [==============================] - 6s 19us/step - loss: 0.6922 - val_loss: 0.6933
Epoch 5/10
336830/336830 [==============================] - 6s 19us/step - loss: 0.6920 - val_loss: 0.6951
Epoch 6/10
336830/336830 [==============================] - 7s 19us/step - loss: 0.6918 - val_loss: 0.6949
Epoch 7/10
336830/336830 [==============================] - 6s 19us/step - loss: 0.6916 - val_loss: 0.6941
Epoch 8/10
336830/336830 [==============================] - 6s 19us/step - loss: 0.6914 - val_loss: 0.6937
Epoch 9/10
336830/336830 [==============================] - 6s 19us/step - loss: 0.6912 - va

In [ ]:
    m4 = Dense(25)(m3)
    m4 = Activation('sigmoid')(m4)
    m4 = Dropout(dropout)(m4) 